### ISSUE TITLE
Script include doesn't seem to work when using `defer`

### ISSUE THREAD

**Issue by rnarian** [FA-Minify/gulp-fa-minify#2]
![image](https://user-images.githubusercontent.com/1174951/42990967-8aa6ed52-8c04-11e8-9378-592cd731b8f8.png)

I had to make this change to get it to work. Strangely the `fab` icons work even with using `defer`, the `fas` icons do not.

**Comment by rnarian** [comment]
Ignore for now. Don't know what went wrong here first, but it seems to work fine now. 🤔💭

**Comment by philiprekers** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/a00419f8-8390-4472-b1c4-20236d8783ca-76c8f77d-491f-461f-8e95-f60b0d075c3d-v1.png?transparent=1&palette=1&width=246)

**Comment by NetWin** [comment]
never heard of it again
#closed
